# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

general:
  istep: 0

training_config:
  num_mini_epochs: 16

  model_input:
    masking:
      masking_strategy: "forecast"

  forecast:
    time_step: "06:00:00"
    offset: 1
    num_steps: 8
    policy: "fixed"
